spring.application.name=Spring-Monitoring-Basic
server.port=8080

#Actuator Port
management.server.port=8081
#management.endpoints.web.exposure.include=health,info,metrics,prometheus,httptrace,beans,mappings,configprops,shutdown,loggers
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


# You can shutdown app with this endpoint
management.endpoint.shutdown.enabled=true


slack.webhook.url = https://hooks.slack.com/services/...../...../.....


